from typing import Any, Callable, Optional, TypeVar, overload

T = TypeVar("T")

@overload
def Header(alias: Optional[str] = None, *, required: bool = False) -> Any: ...
@overload
def Header(alias: Optional[str] = None, *, default: T, required: bool = False) -> T: ...
@overload
def Header(
    alias: Optional[str] = None,
    *,
    default_factory: Callable[[], T],
    required: bool = False,
) -> T: ...
@overload
def Query(alias: Optional[str] = None, *, required: bool = False) -> Any: ...
@overload
def Query(alias: Optional[str] = None, *, default: T, required: bool = False) -> T: ...
@overload
def Query(
    alias: Optional[str] = None,
    *,
    default_factory: Callable[[], T],
    required: bool = False,
) -> T: ...
@overload
def Path(alias: Optional[str] = None, *, required: bool = False) -> Any: ...
@overload
def Path(alias: Optional[str] = None, *, default: T, required: bool = False) -> T: ...
@overload
def Path(
    alias: Optional[str] = None,
    *,
    default_factory: Callable[[], T],
    required: bool = False,
) -> T: ...
@overload
def Cookie(alias: Optional[str] = None, *, required: bool = False) -> Any: ...
@overload
def Cookie(alias: Optional[str] = None, *, default: T, required: bool = False) -> T: ...
@overload
def Cookie(
    alias: Optional[str] = None,
    *,
    default_factory: Callable[[], T],
    required: bool = False,
) -> T: ...
@overload
def Body(
    alias: Optional[str] = None, *, required: bool = False, embed: bool = False
) -> Any: ...
@overload
def Body(
    alias: Optional[str] = None,
    *,
    default: T,
    required: bool = False,
    embed: bool = False,
) -> T: ...
@overload
def Body(
    alias: Optional[str] = None,
    *,
    default_factory: Callable[[], T],
    required: bool = False,
    embed: bool = False,
) -> T: ...
@overload
def Headers() -> Any: ...
@overload
def Headers(*, default: T) -> T: ...
@overload
def Headers(*, default_factory: Callable[[], T]) -> T: ...
@overload
def QueryParams() -> Any: ...
@overload
def QueryParams(*, default: T) -> T: ...
@overload
def QueryParams(*, default_factory: Callable[[], T]) -> T: ...
@overload
def Cookies() -> Any: ...
@overload
def Cookies(*, default: T) -> T: ...
@overload
def Cookies(*, default_factory: Callable[[], T]) -> T: ...
@overload
def PathParams() -> Any: ...
@overload
def PathParams(*, default: T) -> T: ...
@overload
def PathParams(*, default_factory: Callable[[], T]) -> T: ...
@overload
def Depends(*, use_cache: bool = True) -> Any: ...
@overload
def Depends(dependency: Callable[..., T], /, *, use_cache: bool = True) -> T: ...
@overload
def Promise() -> Any: ...
@overload
def Promise(promised_type: T, /) -> T: ...
