from typing import Any, Optional, TypeVar, overload

T = TypeVar("T")

@overload
def Header(name: Optional[str] = None) -> Any: ...
@overload
def Header(name: Optional[str] = None, *, default: T) -> T: ...
@overload
def Query(name: Optional[str] = None) -> Any: ...
@overload
def Query(name: Optional[str] = None, *, default: T) -> T: ...
@overload
def Path(name: Optional[str] = None) -> Any: ...
@overload
def Path(name: Optional[str] = None, *, default: T) -> T: ...
@overload
def Cookie(name: Optional[str] = None) -> Any: ...
@overload
def Cookie(name: Optional[str] = None, *, default: T) -> T: ...
def Headers() -> Any:
    ...
def Queries() -> Any:
    ...
def Cookies() -> Any:
    ...